version: "3.5"

services:
  db:
    container_name: unifier-db
    image: postgres:12.3-alpine
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432

  app:
    container_name: unifier
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "${DJANGO_BIND_PORT}:${DJANGO_BIND_PORT}"
    depends_on:
      - db
    command: 
      [
        "./scripts/wait-for-it.sh",
        "${DB_HOST}:${DB_PORT}",
        "-t",
        "120",
        "--",
        "./scripts/start.sh",
      ]

  integration-tests:
    image: python:3.8-slim-buster
    env_file: .env
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - db
    command: 
      [
        "./scripts/wait-for-it.sh",
        "${DB_HOST}:${DB_PORT}",
        "-t",
        "120",
        "--",
        "sh",
        "-c",
        "pip install tox && tox"
      ]
