# Generated by Django 3.1.6 on 2021-02-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210216_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='status',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='novel',
            name='status',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Status'),
        ),
    ]
