# Generated by Django 3.1.6 on 2021-02-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210216_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='path',
            field=models.URLField(max_length=256, verbose_name='Image path URL'),
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.URLField(max_length=256, verbose_name='Image URL'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='cover',
            field=models.URLField(blank=True, max_length=256, null=True, verbose_name='Cover URL'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='cover',
            field=models.URLField(blank=True, max_length=256, null=True, verbose_name='Cover URL'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='url',
            field=models.URLField(max_length=256, verbose_name='Platform URL'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='url_search',
            field=models.URLField(max_length=256, verbose_name='Platform search URL'),
        ),
    ]
