# Generated by Django 3.1.6 on 2021-02-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210216_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Manga description'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Novel description'),
        ),
        migrations.AlterField(
            model_name='novelchapter',
            name='body',
            field=models.TextField(verbose_name='Novel content'),
        ),
    ]
