# Generated by Django 3.1.6 on 2021-02-16 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210216_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='path',
            field=models.URLField(blank=True, max_length=256, null=True, verbose_name='Image path URL'),
        ),
    ]
