# Generated by Django 3.1.6 on 2021-02-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210216_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='mangas',
            field=models.ManyToManyField(blank=True, related_name='platform', to='core.Manga'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='novels',
            field=models.ManyToManyField(blank=True, related_name='platform', to='core.Novel'),
        ),
    ]
