# Generated by Django 3.1.6 on 2021-02-23 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210219_1445'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manga',
            options={'ordering': ('year',), 'verbose_name': 'Manga', 'verbose_name_plural': 'Mangas'},
        ),
        migrations.AlterModelOptions(
            name='mangachapter',
            options={'ordering': ('number',), 'verbose_name': 'Manga Chapter', 'verbose_name_plural': 'Manga Chapters'},
        ),
        migrations.AlterModelOptions(
            name='novel',
            options={'ordering': ('year',), 'verbose_name': 'Novel', 'verbose_name_plural': 'Novels'},
        ),
        migrations.AlterModelOptions(
            name='novelchapter',
            options={'ordering': ('number',), 'verbose_name': 'Novel Chapter', 'verbose_name_plural': 'Novel Chapters'},
        ),
    ]
