# Generated by Django 3.1.7 on 2021-03-02 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210225_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='tags',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Tags'),
        ),
    ]
