# Generated by Django 3.1.7 on 2021-05-04 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_favorite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Favorite', 'verbose_name_plural': 'Favorites'},
        ),
    ]
