name: Integration Tests
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DJANGO_BIND_PORT: ${{ secrets.DJANGO_BIND_PORT }}
    steps:
      - name: Env values
        run: echo "${{ secrets.DB_HOST }} ${{ secrets.DB_PORT }} ${{ secrets.DJANGO_BIND_PORT }}"
      - name: Working copy
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Build project
        run: docker-compose build --no-cache  integration-tests
      - name: Tests
        run: docker-compose up --exit-code-from  integration-tests  integration-tests
